# 模仿Jackal的control.yaml，为Husky创建
controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    # 这部分与Jackal保持一致
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # 将控制器重命名为 husky_velocity_controller
    husky_velocity_controller:
      type: diff_drive_controller/DiffDriveController

husky_velocity_controller:
  ros__parameters:
    # 轮子关节名与Husky匹配 (front/rear, left/right)
    left_wheel_names: [ "front_left_wheel_joint", "rear_left_wheel_joint" ]
    right_wheel_names: [ "front_right_wheel_joint", "rear_right_wheel_joint" ]

    # --- 核心修改：更新为Husky的物理参数 ---
    wheel_separation: 0.54
    wheel_radius: 0.1651
    # -----------------------------------------

    # 其他参数与Jackal保持一致，以确保稳定性
    wheel_separation_multiplier: 1.5
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.03, 1000000.0, 1000000.0, 0.03]

    open_loop: false
    enable_odom_tf: true # 通常我们希望发布odom->base_link的TF

    cmd_vel_timeout: 0.25
    use_stamped_vel: false
    preserve_turning_radius: true
    publish_cmd: true
    publish_wheel_data: true

    # 速度和加速度限制
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.max_velocity: 2.0
    linear.x.min_velocity: -2.0
    linear.x.max_acceleration: 20.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.max_velocity: 4.0
    angular.z.max_acceleration: 25.0
