controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    # Joint State Broadcaster
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Velocity Controller for Dingo
    dingo_velocity_controller: # MODIFIED from jackal_velocity_controller
      type: diff_drive_controller/DiffDriveController

dingo_velocity_controller: # MODIFIED from jackal_velocity_controller
  ros__parameters:
    # URDF joint names for Dingo's wheels - MUST BE VERIFIED FROM DINGO'S URDF
    left_wheel_names: ["dingo_front_left_wheel_joint", "dingo_rear_left_wheel_joint"] # EXAMPLE - REPLACE WITH ACTUAL NAMES
    right_wheel_names: ["dingo_front_right_wheel_joint", "dingo_rear_right_wheel_joint"] # EXAMPLE - REPLACE WITH ACTUAL NAMES

    # Physical properties of Dingo
    wheel_separation: 0.43     # ESTIMATE for Dingo (meters) - VERIFY/TUNE
    # wheels_per_side: 1       # Or 2, depending on preference if controller handles listed joints
    wheel_radius: 0.11         # ESTIMATE for Dingo (meters) - VERIFY FROM URDF/MESH

    # Multipliers for skid-steer behavior
    wheel_separation_multiplier: 1.5 # Common for skid-steer, may need tuning
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # Publishing and TF frames
    publish_rate: 50.0
    odom_frame_id: odom        # Typically namespaced by controller based on its launch context
    base_frame_id: base_link   # Typically namespaced by controller

    # Odometry covariance (can be tuned)
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03] # Adjusted twist covariance for x, y based on typical diff_drive

    open_loop: false
    enable_odom_tf: false      # Set to true if controller should publish odom->base_link TF

    # Command timeout
    cmd_vel_timeout: 0.25
    use_stamped_vel: false

    # Preserve turning radius when limiting speed
    preserve_turning_radius: true

    # Publish limited velocity command
    publish_cmd: true
    publish_wheel_data: true # Useful for debugging

    # Velocity and acceleration limits for Dingo-D
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false # Typically false unless very fine control needed
    linear.x.max_velocity: 1.3      # MODIFIED - Dingo-D Max Speed
    linear.x.min_velocity: -1.3     # MODIFIED - Dingo-D Max Speed
    linear.x.max_acceleration: 3.0  # ADJUSTED - More realistic acceleration
    linear.x.min_acceleration: -3.0 # ADJUSTED - More realistic acceleration
    # linear.x.max_jerk: 0.0
    # linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false # Typically false
    angular.z.max_velocity: 3.0     # ADJUSTED - More conservative angular velocity
    angular.z.min_velocity: -3.0    # ADJUSTED - More conservative angular velocity
    angular.z.max_acceleration: 5.0 # ADJUSTED - More realistic angular acceleration
    angular.z.min_acceleration: -5.0# ADJUSTED - More realistic angular acceleration
    # angular.z.max_jerk: 0.0
    # angular.z.min_jerk: 0.0