/**:
  controller_manager:
    ros__parameters:
      use_sim_time: true
      update_rate: 100  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      robotnik_base_controller:
        type: robotnik_controllers/RBTheronController

  joint_state_broadcaster:
    ros__parameters:
      use_sim_time: true
      publish_rate: 200

  robotnik_base_controller:
    ros__parameters:
      use_sim_time: true
      publish_rate: 200

      #General Params
      profile_list: ["base"]
      profile: base
      debug: true
      open_loop: true

      #Timeouts
      joint_command_timeout: 0.1
      imu_timeout: 0.2
      cmd_vel_timeout: 1.0

      #Topics
      cmd_vel_topic: ~/cmd_vel
      odom_topic: ~/odom
      imu_topic: /robot/imu/data
      emergency_topic: ~/emergency
      joint_control_topic: ~/joint_control_command

      #Odom
      odom_frame_id: robot_odom
      base_frame_id: robot_base_footprint
      set_odometry_service: ~/set_odometry

      #Imu
      use_imu: true

      #Kinematics Params
      wheel_radius: 0.0762
      track_width:  0.5032
      wheel_base: 0.458

      max_steering_position_error: 0.3

      wheels_positions: ["right", "left"]

      #Cartesian and wheels limits
      base:
        linear:
          x:
            velocity:
              min: -1.0
              max:  1.0
            acceleration:
              min: -5.0
              max:  5.0
          y:
            velocity:
              min: -1.0
              max:  1.0
            acceleration:
              min: -5.0
              max:  5.0
        angular:
          z:
            velocity:
              min: -1.0
              max:  1.0
            acceleration:
              min: -5.0
              max:  5.0
        right:
          traction:
            joint_name: robot_right_wheel_joint
            limits:
              velocity:
                min: -27.7
                max:  27.7
              acceleration:
                min: -10.0
                max:  10.0

        left:
          traction:
            joint_name: robot_left_wheel_joint
            limits:
              velocity:
                min: -27.7
                max:  27.7
              acceleration:
                min: -10.0
                max:  10.0
