<?xml version="1.0"?>
<robot name="sensor_intel_realsense_d435i" xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:include filename="$(find arena_robots)/robots/rbkairos/urdf/depth/depth_camera_plugin.urdf.xacro" />
  <xacro:include filename="$(find arena_robots)/robots/rbkairos/urdf/depth/irred_camera_plugin.urdf.xacro" />
  <xacro:include filename="$(find arena_robots)/robots/rbkairos/urdf/camera/camera_plugin.urdf.xacro" />
  <xacro:include filename="$(find arena_robots)/robots/rbkairos/urdf/imu/imu_plugin.urdf.xacro" />

  <xacro:macro name="sensor_intel_realsense_d435i"
               params="frame_prefix
                       parent
                       *origin
                       gazebo_classic:=false
                       gazebo_ignition:=false
                       node_name:=realsense_d435i
                       node_namespace:=${None}
                       topic_prefix:=~/">
    <!-- node_namespace is used from node_name if not set -->
    <xacro:if value="${node_namespace == None}">
      <xacro:property name="node_namespace" value="${node_name}"/>
    </xacro:if>

    <!-- The following values are approximate, and the camera node
     publishing TF values with actual calibrated camera extrinsic values -->
    <xacro:property name="d435_cam_depth_to_infra1_offset" value="0.0"/>
    <xacro:property name="d435_cam_depth_to_infra2_offset" value="-0.050"/>
    <xacro:property name="d435_cam_depth_to_color_offset" value="0.015"/>

    <!-- The following values model the aluminum peripherial case for the
    D435 camera, with the camera joint represented by the actual
    peripherial camera tripod mount -->
    <xacro:property name="d435_cam_width" value="0.090"/>
    <xacro:property name="d435_cam_height" value="0.025"/>
    <xacro:property name="d435_cam_depth" value="0.02505"/>
    <xacro:property name="d435_cam_mount_from_center_offset" value="0.0149"/>

    <!-- The following offset is relative the the physical D435 camera peripherial
    camera tripod mount -->
    <xacro:property name="d435_cam_depth_px" value="${d435_cam_mount_from_center_offset}"/>
    <xacro:property name="d435_cam_depth_py" value="0.0175"/>
    <xacro:property name="d435_cam_depth_pz" value="${d435_cam_height/2}"/>

    <joint name="${frame_prefix}base_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${frame_prefix}base_link" />
    </joint>
    <link name="${frame_prefix}base_link" />

    <!-- camera body, with origin at bottom screw mount -->
    <joint name="${frame_prefix}joint" type="fixed">
      <parent link="${frame_prefix}base_link" />
      <child link="${frame_prefix}link" />
      <origin xyz="0.01 0.02 0" rpy="0 0 0"/>
      <child link="${frame_prefix}link" />
    </joint>
    <link name="${frame_prefix}link"> <!-- camera link is aligned with the infrared sensor 1 that is "in the middle of the camera", not the one in the edge -->
      <visual>
        <origin xyz="${d435_cam_mount_from_center_offset} ${-d435_cam_depth_py} 0" rpy="${pi/2} 0 ${pi/2}"/>
        <geometry>
          <!-- <box size="${d435_cam_width} ${d435_cam_height} ${d435_cam_depth}"/> -->
          <mesh filename="package://arena_robots/robots/rbkairos/meshes/depth/intel_realsense_d435/intel_d435_color.dae" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 ${-d435_cam_depth_py} 0" rpy="0 0 0"/>
        <geometry>
          <box size="${d435_cam_depth} ${d435_cam_width} ${d435_cam_height}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0.0025 -0.015 0.0" rpy="0 0 0" />
        <mass value="0.1" />
        <xacro:solid_cuboid_inertia m="0.1" w="0.025" h="0.09" d="0.025" />
      </inertial>
    </link>

    <!-- Use the nominal extrinsics between camera frames if the calibrated extrinsics aren't being published. e.g. running the device in simulation  -->
      <!-- camera depth joints and links -->
      <joint name="${frame_prefix}depth_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="${frame_prefix}link"/>
        <child link="${frame_prefix}depth_frame" />
      </joint>
      <link name="${frame_prefix}depth_frame"/>

      <joint name="${frame_prefix}depth_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
        <parent link="${frame_prefix}depth_frame" />
        <child link="${frame_prefix}depth_optical_frame" />
      </joint>
      <link name="${frame_prefix}depth_optical_frame"/>

      <!-- camera left IR joints and links -->
      <joint name="${frame_prefix}infra1_joint" type="fixed">
        <origin xyz="0 ${d435_cam_depth_to_infra1_offset} 0" rpy="0 0 0" />
        <parent link="${frame_prefix}link" />
        <child link="${frame_prefix}infra1_frame" />
      </joint>
      <link name="${frame_prefix}infra1_frame"/>

      <joint name="${frame_prefix}infra1_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
        <parent link="${frame_prefix}infra1_frame" />
        <child link="${frame_prefix}infra1_optical_frame" />
      </joint>
      <link name="${frame_prefix}infra1_optical_frame"/>

      <!-- camera right IR joints and links -->
      <joint name="${frame_prefix}infra2_joint" type="fixed">
        <origin xyz="0 ${d435_cam_depth_to_infra2_offset} 0" rpy="0 0 0" />
        <parent link="${frame_prefix}link" />
        <child link="${frame_prefix}infra2_frame" />
      </joint>
      <link name="${frame_prefix}infra2_frame"/>

      <joint name="${frame_prefix}infra2_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
        <parent link="${frame_prefix}infra2_frame" />
        <child link="${frame_prefix}infra2_optical_frame" />
      </joint>
      <link name="${frame_prefix}infra2_optical_frame"/>

      <!-- camera color joints and links -->
      <joint name="${frame_prefix}color_joint" type="fixed">
        <origin xyz="0 ${d435_cam_depth_to_color_offset} 0" rpy="0 0 0" />
        <parent link="${frame_prefix}link" />
        <child link="${frame_prefix}color_frame" />
      </joint>
      <link name="${frame_prefix}color_frame"/>

      <joint name="${frame_prefix}color_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
        <parent link="${frame_prefix}color_frame" />
        <child link="${frame_prefix}color_optical_frame" />
      </joint>
      <link name="${frame_prefix}color_optical_frame"/>

      <!-- Imu frame -->
      <joint name="${frame_prefix}imu_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="${frame_prefix}link" />
        <child link="${frame_prefix}imu_frame" />
      </joint>
      <link name="${frame_prefix}imu_frame"/>

      <xacro:camera_plugin
        node_namespace="${node_namespace}"
        node_name="${node_name}_color"
        topic_prefix="${topic_prefix}_color"
        gazebo_classic="${gazebo_classic}"
        gazebo_ignition="${gazebo_ignition}"
        optical_frame="${frame_prefix}color_optical_frame"
        reference_frame="${frame_prefix}color_frame"
        horizontal_fov="69.4"
        vertical_fov="39"
        video_width="1920"
        video_height="1080"
        min_depth="0.1"
        max_depth="100"
        rate="30"
      >
      </xacro:camera_plugin>

      <xacro:irred_camera_plugin
        node_namespace="${node_namespace}"
        node_name="${node_name}_irred1"
        topic_prefix="${topic_prefix}_irred1"
        gazebo_classic="${gazebo_classic}"
        gazebo_ignition="${gazebo_ignition}"
        optical_frame="${frame_prefix}infra1_optical_frame"
        reference_frame="${frame_prefix}infra2_frame"
        horizontal_fov="85.2"
        vertical_fov="48"
        video_width="1280"
        video_height="720"
        min_depth="0.1"
        max_depth="100"
        rate="30"
      >
      </xacro:irred_camera_plugin>

      <xacro:irred_camera_plugin
        node_namespace="${node_namespace}"
        node_name="${node_name}_irred2"
        topic_prefix="${topic_prefix}_irred2"
        gazebo_classic="${gazebo_classic}"
        gazebo_ignition="${gazebo_ignition}"
        optical_frame="${frame_prefix}infra2_optical_frame"
        reference_frame="${frame_prefix}infra2_frame"
        horizontal_fov="85.2"
        vertical_fov="48"
        video_width="1280"
        video_height="720"
        min_depth="0.1"
        max_depth="100"
        rate="30"
      >
      </xacro:irred_camera_plugin>

      <xacro:depth_camera_plugin
        node_namespace="${node_namespace}"
        node_name="${node_name}_depth"
        topic_prefix="${topic_prefix}_depth"
        gazebo_classic="${gazebo_classic}"
        gazebo_ignition="${gazebo_ignition}"
        optical_frame="${frame_prefix}depth_optical_frame"
        reference_frame="${frame_prefix}depth_frame"
        horizontal_fov="85.2"
        vertical_fov="48"
        video_width="1280"
        video_height="720"
        min_depth="0.1"
        max_depth="100"
        rate="30"
      >
      </xacro:depth_camera_plugin>

      <!-- <gazebo>
        <plugin name="${node_name}" filename="librealsense_gazebo_plugin.so">
          <prefix>${node_namespace}</prefix>
          <depthUpdateRate>60.0</depthUpdateRate>
          <colorUpdateRate>60.0</colorUpdateRate>
          <infraredUpdateRate>60.0</infraredUpdateRate>
          <depthTopicName>${topic_prefix}depth/image_rect_raw</depthTopicName>
          <depthCameraInfoTopicName>${topic_prefix}depth/camera_info</depthCameraInfoTopicName>
          <colorTopicName>${topic_prefix}color/image_raw</colorTopicName>
          <colorCameraInfoTopicName>${topic_prefix}color/camera_info</colorCameraInfoTopicName>
          <infrared1TopicName>${topic_prefix}infra1/image_raw</infrared1TopicName>
          <infrared1CameraInfoTopicName>${topic_prefix}infra1/camera_info</infrared1CameraInfoTopicName>
          <infrared2TopicName>${topic_prefix}infra2/image_raw</infrared2TopicName>
          <infrared2CameraInfoTopicName>${topic_prefix}infra2/camera_info</infrared2CameraInfoTopicName>
          <colorOpticalframeName>${frame_prefix}color_optical_frame</colorOpticalframeName>
          <depthOpticalframeName>${frame_prefix}depth_optical_frame</depthOpticalframeName>
          <infrared1OpticalframeName>${frame_prefix}infra1_optical_frame</infrared1OpticalframeName>
          <infrared2OpticalframeName>${frame_prefix}infra2_optical_frame</infrared2OpticalframeName>
          <rangeMinDepth>0.2</rangeMinDepth>
          <rangeMaxDepth>10.0</rangeMaxDepth>
          <pointCloud>true</pointCloud>
          <pointCloudTopicName>${topic_prefix}depth/color/points</pointCloudTopicName>
          <pointCloudCutoff>0.5</pointCloudCutoff>
        </plugin>
      </gazebo> -->

      <!-- Imu -->

    <xacro:imu_plugin
      node_namespace="${node_namespace}"
      node_name="${node_name}"
      gazebo_classic="${gazebo_classic}"
      gazebo_ignition="${gazebo_ignition}"
      frame_link="${frame_prefix}link"
      rate="200.0"
    >
    </xacro:imu_plugin>
  </xacro:macro>
</robot>
