/**:
  controller_manager:
    ros__parameters:
      use_sim_time: true
      update_rate: 50  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      robotnik_base_controller:
        type: robotnik_controllers/RBVoguiController

  joint_state_broadcaster:
    ros__parameters:
      use_sim_time: true
      publish_rate: 50

  robotnik_base_controller:
    ros__parameters:
      use_sim_time: true
      publish_rate: 50

      #General Params
      profile: base
      debug: true
      open_loop: true

      #Timeouts
      joint_command_timeout: 0.1
      cmd_vel_timeout: 0.5

      #Odom
      odom_frame_id: robot_odom
      base_frame_id: robot_base_footprint
      use_2D_odom: true

      #Kinematics Params
      wheel_radius: 0.1125    #0.2552
      wheel_base:   0.76      #0.43
      track_width:  0.4745    #0.538
      min_turning_ratio:  1.0

      max_steering_position_error: 0.3

      #Cartesian and wheels limits
      base:
        linear:
          x:
            velocity:
              min: -0.3
              max:  0.3
            acceleration:
              min: -1.0
              max:  1.0
          y:
            velocity:
              min: -0.3
              max:  0.3
            acceleration:
              min: -1.0
              max:  1.0
        angular:
          z:
            velocity:
              min: -0.3
              max:  0.3
            acceleration:
              min: -1.0
              max:  1.0

        front_right:
          traction:
            joint_name: robot_front_right_wheel_joint
            limits:
              velocity:
                min: -3.0
                max:  3.0
              acceleration:
                min: -10.0
                max:  10.0
          steering:
            joint_name: robot_front_right_steering_joint
            limits:
              velocity:
                min: -1.0
                max:  1.0
              position:
                min: -2.8
                max:  2.8

        front_left:
          traction:
            joint_name: robot_front_left_wheel_joint
            limits:
              velocity:
                min: -3.0
                max:  3.0
              acceleration:
                min: -10.0
                max:  10.0
          steering:
            joint_name: robot_front_left_steering_joint
            limits:
              velocity:
                min: -1.0
                max:  1.0
              position:
                min: -2.8
                max:  2.8

        back_right:
          traction:
            joint_name: robot_back_right_wheel_joint
            limits:
              velocity:
                min: -3.0
                max:  3.0
              acceleration:
                min: -10.0
                max:  10.0
          steering:
            joint_name: robot_back_right_steering_joint
            limits:
              velocity:
                min: -1.0
                max:  1.0
              position:
                min: -2.8
                max:  2.8

        back_left:
          traction:
            joint_name: robot_back_left_wheel_joint
            limits:
              velocity:
                min: -3.0
                max:  3.0
              acceleration:
                min: -10.0
                max:  10.0
          steering:
            joint_name: robot_back_left_steering_joint
            limits:
              velocity:
                min: -1.0
                max:  1.0
              position:
                min: -2.8
                max:  2.8
